import { CropMetadata, CropType } from '../types';

export const CROP_METADATA_REGISTRY: Record<CropType, CropMetadata> = {
  Wheat: {
    name: 'Wheat',
    variety: 'Sharbati PBW-550',
    shelfLifeDays: 365,
    perishability: 'Durable (Non-Perishable)',
    requiresColdChain: false,
    idealTempCelsius: '18°C - 25°C (Ambient dry)',
    maxLogisticsRadiusKm: 2500,
    baseLogisticsRatePerKmKg: 0.003,
    standardYieldUnit: 'kg',
    icon: '🌾',
    defaultPricePerKg: 10,
    description: 'Staple grain with high shelf-stability. Feasible for cross-country long-haul distribution into any dark store hub.'
  },
  Tomatoes: {
    name: 'Tomatoes',
    variety: 'Roma Organic Hybrid',
    shelfLifeDays: 5,
    perishability: 'Highly Perishable',
    requiresColdChain: true,
    idealTempCelsius: '12°C - 15°C (Chilled ambient)',
    maxLogisticsRadiusKm: 380,
    baseLogisticsRatePerKmKg: 0.008,
    standardYieldUnit: 'kg',
    icon: '🍅',
    defaultPricePerKg: 18,
    description: 'Fast-ripening crop requiring regional dark store hubs within ~350 km to prevent spoilage and pressure bruising.'
  },
  'Basmati Rice': {
    name: 'Basmati Rice',
    variety: 'Pusa 1121 Extra Long Grain',
    shelfLifeDays: 365,
    perishability: 'Durable (Non-Perishable)',
    requiresColdChain: false,
    idealTempCelsius: 'Ambient dry storage',
    maxLogisticsRadiusKm: 2500,
    baseLogisticsRatePerKmKg: 0.0032,
    standardYieldUnit: 'kg',
    icon: '🍚',
    defaultPricePerKg: 48,
    description: 'Premium aromatic grain with extensive shelf stability, suitable for national delivery networks.'
  },
  Apples: {
    name: 'Apples',
    variety: 'Royal Delicious Mountain Grade',
    shelfLifeDays: 35,
    perishability: 'Semi-Perishable',
    requiresColdChain: true,
    idealTempCelsius: '1°C - 4°C (Controlled atmosphere)',
    maxLogisticsRadiusKm: 1400,
    baseLogisticsRatePerKmKg: 0.006,
    standardYieldUnit: 'kg',
    icon: '🍎',
    defaultPricePerKg: 65,
    description: 'Himalayan orchard produce with cold chain requirement for cross-state transit to metropolitan hubs.'
  },
  Potatoes: {
    name: 'Potatoes',
    variety: 'Kufri Jyoti Table',
    shelfLifeDays: 60,
    perishability: 'Semi-Perishable',
    requiresColdChain: false,
    idealTempCelsius: '10°C - 14°C (Ventilated cool)',
    maxLogisticsRadiusKm: 1200,
    baseLogisticsRatePerKmKg: 0.004,
    standardYieldUnit: 'kg',
    icon: '🥔',
    defaultPricePerKg: 14,
    description: 'Moderate shelf life tuber crop, requires light-protected dry transport.'
  },
  Strawberries: {
    name: 'Strawberries',
    variety: 'Sweet Charlie Hydroponic',
    shelfLifeDays: 3,
    perishability: 'Highly Perishable',
    requiresColdChain: true,
    idealTempCelsius: '2°C - 4°C (Active reefer)',
    maxLogisticsRadiusKm: 220,
    baseLogisticsRatePerKmKg: 0.012,
    standardYieldUnit: 'kg',
    icon: '🍓',
    defaultPricePerKg: 120,
    description: 'Extremely delicate berry. Strictly routed to proximate urban dark stores with refrigerated last-mile couriers.'
  },
  Onions: {
    name: 'Onions',
    variety: 'Nashik Red Pusa',
    shelfLifeDays: 75,
    perishability: 'Semi-Perishable',
    requiresColdChain: false,
    idealTempCelsius: 'Ventilated dry 15°C - 20°C',
    maxLogisticsRadiusKm: 1500,
    baseLogisticsRatePerKmKg: 0.0038,
    standardYieldUnit: 'kg',
    icon: '🧅',
    defaultPricePerKg: 16,
    description: 'High storage resilience, susceptible to moisture dampness during transit.'
  },
  'Mustard Seed': {
    name: 'Mustard Seed',
    variety: 'Pusa Bold High-Oil',
    shelfLifeDays: 300,
    perishability: 'Durable (Non-Perishable)',
    requiresColdChain: false,
    idealTempCelsius: 'Dry room temperature',
    maxLogisticsRadiusKm: 2500,
    baseLogisticsRatePerKmKg: 0.003,
    standardYieldUnit: 'kg',
    icon: '🌱',
    defaultPricePerKg: 52,
    description: 'Oilseed crop with exceptional storage durability and easy long-distance logistics.'
  },
  Cotton: {
    name: 'Cotton',
    variety: 'BT Long Staple 32mm',
    shelfLifeDays: 365,
    perishability: 'Durable (Non-Perishable)',
    requiresColdChain: false,
    idealTempCelsius: 'Dry storage',
    maxLogisticsRadiusKm: 2500,
    baseLogisticsRatePerKmKg: 0.003,
    standardYieldUnit: 'kg',
    icon: '🌾',
    defaultPricePerKg: 68,
    description: 'Long-staple ginning cotton, non-perishable agricultural commodity.'
  },
  'Green Chillies': {
    name: 'Green Chillies',
    variety: 'Guntur Teja Spicy',
    shelfLifeDays: 10,
    perishability: 'Perishable',
    requiresColdChain: false,
    idealTempCelsius: '12°C - 15°C (Ventilated cool)',
    maxLogisticsRadiusKm: 800,
    baseLogisticsRatePerKmKg: 0.005,
    standardYieldUnit: 'kg',
    icon: '🌶️',
    defaultPricePerKg: 34,
    description: 'Fresh spicy green chillies, packed in aerated crates to prevent condensation.'
  },
  Soybean: {
    name: 'Soybean',
    variety: 'JS-335 High Protein',
    shelfLifeDays: 180,
    perishability: 'Durable (Non-Perishable)',
    requiresColdChain: false,
    idealTempCelsius: 'Ambient dry',
    maxLogisticsRadiusKm: 2500,
    baseLogisticsRatePerKmKg: 0.003,
    standardYieldUnit: 'kg',
    icon: '🌱',
    defaultPricePerKg: 42,
    description: 'Non-GMO protein-dense soybean, clean moisture-tested grain.'
  },
  'Pulses (Arhar)': {
    name: 'Pulses (Arhar)',
    variety: 'Unpolished Desi Toor',
    shelfLifeDays: 365,
    perishability: 'Durable (Non-Perishable)',
    requiresColdChain: false,
    idealTempCelsius: 'Ambient dry storage',
    maxLogisticsRadiusKm: 2500,
    baseLogisticsRatePerKmKg: 0.003,
    standardYieldUnit: 'kg',
    icon: '🍲',
    defaultPricePerKg: 78,
    description: 'Pure unpolished Arhar Dal, dry storage stability.'
  }
};
